########################################
# 由于 GitHub API 限制，最多可以设置 60 个
########################################

links:
  ######## Stellar ########
  # Stellar 最近更新日志（10条记录）
  - https://api.github.com/repos/Bush2021/chrome_plus/releases?per_page=10
